# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sga_fields_synchronizer}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["tim.teng"]
  s.date = %q{2010-06-23}
  s.description = %q{ A synchronizer for most frequently edited columns based on yml file}
  s.email = %q{tim.rubist@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "generators/fields_synchronizer/fields_synchronizer_generator.rb",
     "generators/fields_synchronizer/templates/fields_dictionary.example",
     "generators/fields_synchronizer/templates/migration.rb",
     "lib/fields_reader.rb",
     "lib/sga_fields_synchronizer.rb",
     "sga_fields_synchronizer.gemspec",
     "test/helper.rb",
     "test/test_sga_fields_synchronizer.rb"
  ]
  s.homepage = %q{http://github.com/tteng/sga_fields_synchronizer}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A synchronizer for most frequently edited columns}
  s.test_files = [
    "test/helper.rb",
     "test/test_sga_fields_synchronizer.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

